In [1]:
from datetime import datetime
import pandas as pd
import numpy as np

In [2]:
# load the data
df = pd.read_csv(r"C:\Users\Dell\Documents\my_linux\repos_\predicting-covid19-infection\predicting_covid19_infection\data\raw\COVID19 - COVID19.csv")
display(df.shape, df.info())

C:\Users\Dell\AppData\Local\Temp\ipykernel_15556\2295218547.py:2: DtypeWarning: Columns (8,9,10,13,16,20,24,32,45) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\Dell\Documents\my_linux\repos_\predicting-covid19-infection\predicting_covid19_infection\data\raw\COVID19 - COVID19.csv")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109927 entries, 0 to 109926
Data columns (total 47 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   Sex                                        107228 non-null  object
 1   Birth Year                                 94963 non-null   float64
 2   Chest pain                                 42120 non-null   object
 3   Chills or sweats                           24857 non-null   object
 4   Confused or disoriented                    23127 non-null   object
 5   Cough                                      42218 non-null   object
 6   Diarrhea                                   42092 non-null   object
 7   Difficulty breathing or Dyspnea            24940 non-null   object
 8   Digested blood or coffee grounds in vomit  1397 non-null    object
 9   Pain behind eyes or Sensitivity to light   1405 non-null    object
 10  Bleeding from the eyes                     1397 non-null    object
 11  Fatigue or general weakness                42158 non-null   object
 12  Fever                                      42229 non-null   object
 13  Fluid in the lung cavity                   1404 non-null    object
 14  Fluid in lung cavity in auscultation       23426 non-null   object
 15  Fluid in cavity through X-Ray              23416 non-null   object
 16  Bleeding of the gums                       1397 non-null    object
 17  Headache                                   42080 non-null   object
 18  Joint pain or arthritis                    24830 non-null   object
 19  Thorax (sore throat)                       40670 non-null   object
 20  Malaise                                    3006 non-null    object
 21  Muscle pain                                23434 non-null   object
 22  Nausea                                     40674 non-null   object
 23  Other clinical symptoms                    23506 non-null   object
 24  Pharyngeal exudate                         2999 non-null    object
 25  Rapid breathing                            22829 non-null   object
 26  Runny nose                                 40677 non-null   object
 27  Maculopapular rash                         21032 non-null   object
 28  Sore throat or pharyngitis                 40670 non-null   object
 29  Bleeding or bruising                       21030 non-null   object
 30  Vomiting                                   40669 non-null   object
 31  Abnormal lung X-Ray findings               23566 non-null   object
 32  Conjunctivitis                             18653 non-null   object
 33  Acute respiratory distress syndrome        23532 non-null   object
 34  Pneumonia (clinical or radiologic)         23414 non-null   object
 35  Loss of Taste                              39837 non-null   object
 36  Loss of Smell                              39829 non-null   object
 37  Cough with sputum                          22181 non-null   object
 38  Cough with heamoptysis                     22180 non-null   object
 39  Enlarged lymph nodes                       21043 non-null   object
 40  Wheezing                                   21025 non-null   object
 41  Skin ulcers                                21023 non-null   object
 42  Inability to walk                          21032 non-null   object
 43  Indrawing of chest wall                    21023 non-null   object
 44  Other complications                        20752 non-null   float64
 45  Specify other complications                5 non-null       object
 46  Result                                     75416 non-null   object
dtypes: float64(2), object(45)
memory usage: 39.4+ MB

(109927, 47)

None

In [3]:
# check for missing values
df.isnull().sum()

Sex                                            2699
Birth Year                                    14964
Chest pain                                    67807
Chills or sweats                              85070
Confused or disoriented                       86800
Cough                                         67709
Diarrhea                                      67835
Difficulty breathing or Dyspnea               84987
Digested blood or coffee grounds in vomit    108530
Pain behind eyes or Sensitivity to light     108522
Bleeding from the eyes                       108530
Fatigue or general weakness                   67769
Fever                                         67698
Fluid in the lung cavity                     108523
Fluid in lung cavity in auscultation          86501
Fluid in cavity through X-Ray                 86511
Bleeding of the gums                         108530
Headache                                      67847
Joint pain or arthritis                       85097
Thorax (sore throat)                          69257
Malaise                                      106921
Muscle pain                                   86493
Nausea                                        69253
Other clinical symptoms                       86421
Pharyngeal exudate                           106928
Rapid breathing                               87098
Runny nose                                    69250
Maculopapular rash                            88895
Sore throat or pharyngitis                    69257
Bleeding or bruising                          88897
Vomiting                                      69258
Abnormal lung X-Ray findings                  86361
Conjunctivitis                                91274
Acute respiratory distress syndrome           86395
Pneumonia (clinical or radiologic)            86513
Loss of Taste                                 70090
Loss of Smell                                 70098
Cough with sputum                             87746
Cough with heamoptysis                        87747
Enlarged lymph nodes                          88884
Wheezing                                      88902
Skin ulcers                                   88904
Inability to walk                             88895
Indrawing of chest wall                       88904
Other complications                           89175
Specify other complications                  109922
Result                                        34511
dtype: int64

In [4]:
df["Result"].value_counts()

Result
NEGATIVE         49371
PENDING          21711
POSITIVE          4330
INDETERMINATE        4
Name: count, dtype: int64

In [5]:
#df["Result"]
dfn = df[(df["Result"] == "PENDING") | (df["Result"] == "NEGATIVE") |\
     (df["Result"] == "POSITIVE") | (df["Result"] == "INDETERMINATE")]
dfn.shape

(75416, 47)

In [6]:
# check for missing values
dfn.info()

<class 'pandas.core.frame.DataFrame'>
Index: 75416 entries, 0 to 109926
Data columns (total 47 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Sex                                        73978 non-null  object
 1   Birth Year                                 63089 non-null  float64
 2   Chest pain                                 40372 non-null  object
 3   Chills or sweats                           23110 non-null  object
 4   Confused or disoriented                    21579 non-null  object
 5   Cough                                      40370 non-null  object
 6   Diarrhea                                   40345 non-null  object
 7   Difficulty breathing or Dyspnea            23098 non-null  object
 8   Digested blood or coffee grounds in vomit  1397 non-null   object
 9   Pain behind eyes or Sensitivity to light   1405 non-null   object
 10  Bleeding from the eyes                     1397 non-null   object
 11  Fatigue or general weakness                40319 non-null  object
 12  Fever                                      40382 non-null  object
 13  Fluid in the lung cavity                   1404 non-null   object
 14  Fluid in lung cavity in auscultation       21679 non-null  object
 15  Fluid in cavity through X-Ray              21669 non-null  object
 16  Bleeding of the gums                       1397 non-null   object
 17  Headache                                   40330 non-null  object
 18  Joint pain or arthritis                    23082 non-null  object
 19  Thorax (sore throat)                       38923 non-null  object
 20  Malaise                                    3005 non-null   object
 21  Muscle pain                                21686 non-null  object
 22  Nausea                                     38930 non-null  object
 23  Other clinical symptoms                    21668 non-null  object
 24  Pharyngeal exudate                         2998 non-null   object
 25  Rapid breathing                            21088 non-null  object
 26  Runny nose                                 38934 non-null  object
 27  Maculopapular rash                         19286 non-null  object
 28  Sore throat or pharyngitis                 38923 non-null  object
 29  Bleeding or bruising                       19286 non-null  object
 30  Vomiting                                   38924 non-null  object
 31  Abnormal lung X-Ray findings               21819 non-null  object
 32  Conjunctivitis                             18653 non-null  object
 33  Acute respiratory distress syndrome        21785 non-null  object
 34  Pneumonia (clinical or radiologic)         21671 non-null  object
 35  Loss of Taste                              38092 non-null  object
 36  Loss of Smell                              38083 non-null  object
 37  Cough with sputum                          20435 non-null  object
 38  Cough with heamoptysis                     20434 non-null  object
 39  Enlarged lymph nodes                       19300 non-null  object
 40  Wheezing                                   19280 non-null  object
 41  Skin ulcers                                19278 non-null  object
 42  Inability to walk                          19287 non-null  object
 43  Indrawing of chest wall                    19278 non-null  object
 44  Other complications                        19205 non-null  float64
 45  Specify other complications                5 non-null      object
 46  Result                                     75416 non-null  object
dtypes: float64(2), object(45)
memory usage: 27.6+ MB

In [7]:
# drop columns were missing values is above 50% of its entire data in the column
dfn = dfn.drop(["Chills or sweats", "Confused or disoriented", "Difficulty breathing or Dyspnea",\
    "Digested blood or coffee grounds in vomit", "Pain behind eyes or Sensitivity to light",\
    "Bleeding from the eyes", "Fluid in the lung cavity", "Fluid in lung cavity in auscultation",\
    "Fluid in cavity through X-Ray", "Bleeding of the gums", "Joint pain or arthritis",\
    "Malaise", "Muscle pain", "Other clinical symptoms", "Pharyngeal exudate", "Rapid breathing",\
    "Maculopapular rash", "Bleeding or bruising", "Abnormal lung X-Ray findings", "Conjunctivitis",\
    "Acute respiratory distress syndrome", "Pneumonia (clinical or radiologic)", "Cough with sputum",\
    "Cough with heamoptysis", "Enlarged lymph nodes", "Wheezing", "Skin ulcers", "Inability to walk",\
    "Indrawing of chest wall", "Other complications", "Specify other complications", ], axis = 1)

In [8]:
display(dfn.shape, dfn.head(3))

(75416, 16)

,Sex,Birth Year,Chest pain,Cough,Diarrhea,Fatigue or general weakness,Fever,Headache,Thorax (sore throat),Nausea,Runny nose,Sore throat or pharyngitis,Vomiting,Loss of Taste,Loss of Smell,Result
0,MALE,1967.0,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,PENDING
2,MALE,1988.0,NO,NO,NO,NO,YES,NO,NO,NO,NO,NO,NO,NaN,NaN,NEGATIVE
4,FEMALE,1978.0,NO,YES,NO,NO,NO,NO,YES,NO,YES,YES,NO,NaN,NaN,NEGATIVE

In [9]:
dfn.info()

<class 'pandas.core.frame.DataFrame'>
Index: 75416 entries, 0 to 109926
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Sex                          73978 non-null  object
 1   Birth Year                   63089 non-null  float64
 2   Chest pain                   40372 non-null  object
 3   Cough                        40370 non-null  object
 4   Diarrhea                     40345 non-null  object
 5   Fatigue or general weakness  40319 non-null  object
 6   Fever                        40382 non-null  object
 7   Headache                     40330 non-null  object
 8   Thorax (sore throat)         38923 non-null  object
 9   Nausea                       38930 non-null  object
 10  Runny nose                   38934 non-null  object
 11  Sore throat or pharyngitis   38923 non-null  object
 12  Vomiting                     38924 non-null  object
 13  Loss of Taste                38092 non-null  object
 14  Loss of Smell                38083 non-null  object
 15  Result                       75416 non-null  object
dtypes: float64(1), object(15)
memory usage: 9.8+ MB

In [10]:
# drop rows with missing date of birth
dfn = dfn.dropna(subset=["Birth Year"])

In [11]:
# evaluate the age from year of birth
# Convert to integer (if needed)
dfn['Birth Year'] = dfn['Birth Year'].astype(int)

# Get the current year
current_year = datetime.now().year

# Compute the age
dfn['age'] = current_year - dfn['Birth Year']

In [12]:
dfn.head(2)

,Sex,Birth Year,Chest pain,Cough,Diarrhea,Fatigue or general weakness,Fever,Headache,Thorax (sore throat),Nausea,Runny nose,Sore throat or pharyngitis,Vomiting,Loss of Taste,Loss of Smell,Result,age
0,MALE,1967,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,PENDING,59
2,MALE,1988,NO,NO,NO,NO,YES,NO,NO,NO,NO,NO,NO,NaN,NaN,NEGATIVE,38

### replace missing values

In [13]:
# Columns where "UNKNOWN" should be replaced with NaN
columns_to_replace_unknown = ["Chest pain", "Cough", 'Diarrhea','Fatigue or general weakness', 'Fever', 'Headache',
                    'Thorax (sore throat)', 'Nausea', 'Runny nose','Sore throat or pharyngitis', 'Vomiting',
                    'Loss of Taste', 'Loss of Smell']  # Only replace in these columns

# Replace "UNKNOWN" with NaN in selected columns only
dfn[columns_to_replace_unknown] = dfn[columns_to_replace_unknown].replace("UNKNOWN", pd.NA)

In [14]:
# Columns to fill missing values for
columns_to_fill = ["Chest pain", "Cough", 'Diarrhea','Fatigue or general weakness', 'Fever', 'Headache',
                    'Thorax (sore throat)', 'Nausea', 'Runny nose','Sore throat or pharyngitis', 'Vomiting',
                    'Loss of Taste', 'Loss of Smell']
                    
# Define conditions
conditions = {
    "child_male": (dfn['Sex'] == 'MALE') & (dfn['age'] < 18),
    "child_female": (dfn['Sex'] == 'FEMALE') & (dfn['age'] < 18),
    "adult_male": (dfn['Sex'] == 'MALE') & (dfn['age'] > 18) & (dfn['age'] < 50),
    "adult_female": (dfn['Sex'] == 'FEMALE') & (dfn['age'] > 18) & (dfn['age'] < 50),
    "old_male": (dfn['Sex'] == 'MALE') & (dfn['age'] > 50),
    "old_female": (dfn['Sex'] == 'FEMALE') & (dfn['age'] > 50),
}

In [15]:
# Fill missing values for each column based on the mode of each condition
for col in columns_to_fill:
    for condition_name, condition in conditions.items():
        subset = dfn.loc[condition, col].dropna()  # Get non-null values for this condition
        if not subset.empty:
            mode_value = subset.mode().iloc[0]  # Get mode (most frequent value)
            dfn.loc[condition & dfn[col].isna(), col] = mode_value  # Fill NaNs only

In [16]:
dfn.info()

<class 'pandas.core.frame.DataFrame'>
Index: 63089 entries, 0 to 109926
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Sex                          62195 non-null  object
 1   Birth Year                   63089 non-null  int32
 2   Chest pain                   61493 non-null  object
 3   Cough                        61493 non-null  object
 4   Diarrhea                     61493 non-null  object
 5   Fatigue or general weakness  61493 non-null  object
 6   Fever                        61494 non-null  object
 7   Headache                     61493 non-null  object
 8   Thorax (sore throat)         61491 non-null  object
 9   Nausea                       61489 non-null  object
 10  Runny nose                   61491 non-null  object
 11  Sore throat or pharyngitis   61491 non-null  object
 12  Vomiting                     61492 non-null  object
 13  Loss of Taste                61474 non-null  object
 14  Loss of Smell                61473 non-null  object
 15  Result                       63089 non-null  object
 16  age                          63089 non-null  int32
dtypes: int32(2), object(15)
memory usage: 8.2+ MB

In [17]:
#
dfn["Sex"].value_counts()

Sex
MALE       41287
FEMALE     20905
UNKNOWN        2
OTHER          1
Name: count, dtype: int64

In [18]:
#
dfn = dfn[(dfn["Sex"] != "UNKNOWN") | (dfn["Sex"] != "OTHER")]
dfn.info()

<class 'pandas.core.frame.DataFrame'>
Index: 63089 entries, 0 to 109926
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Sex                          62195 non-null  object
 1   Birth Year                   63089 non-null  int32
 2   Chest pain                   61493 non-null  object
 3   Cough                        61493 non-null  object
 4   Diarrhea                     61493 non-null  object
 5   Fatigue or general weakness  61493 non-null  object
 6   Fever                        61494 non-null  object
 7   Headache                     61493 non-null  object
 8   Thorax (sore throat)         61491 non-null  object
 9   Nausea                       61489 non-null  object
 10  Runny nose                   61491 non-null  object
 11  Sore throat or pharyngitis   61491 non-null  object
 12  Vomiting                     61492 non-null  object
 13  Loss of Taste                61474 non-null  object
 14  Loss of Smell                61473 non-null  object
 15  Result                       63089 non-null  object
 16  age                          63089 non-null  int32
dtypes: int32(2), object(15)
memory usage: 8.2+ MB

In [19]:
dfn["Sore throat or pharyngitis"].value_counts(dropna=False)

Sore throat or pharyngitis
NO      60979
NaN      1597
YES       512
<NA>        1
Name: count, dtype: int64

In [20]:
# drop missing values that are less than 5% of the population in a column
dfm = dfn.dropna()
dfm.info()

<class 'pandas.core.frame.DataFrame'>
Index: 61241 entries, 0 to 109926
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Sex                          61241 non-null  object
 1   Birth Year                   61241 non-null  int32
 2   Chest pain                   61241 non-null  object
 3   Cough                        61241 non-null  object
 4   Diarrhea                     61241 non-null  object
 5   Fatigue or general weakness  61241 non-null  object
 6   Fever                        61241 non-null  object
 7   Headache                     61241 non-null  object
 8   Thorax (sore throat)         61241 non-null  object
 9   Nausea                       61241 non-null  object
 10  Runny nose                   61241 non-null  object
 11  Sore throat or pharyngitis   61241 non-null  object
 12  Vomiting                     61241 non-null  object
 13  Loss of Taste                61241 non-null  object
 14  Loss of Smell                61241 non-null  object
 15  Result                       61241 non-null  object
 16  age                          61241 non-null  int32
dtypes: int32(2), object(15)
memory usage: 7.9+ MB

In [21]:
# check for duplicate entries
dfm.duplicated().sum()

58747

In [22]:
# 61010 - 58519
dfm = dfm.drop_duplicates(keep="first")
dfm.shape

(2494, 17)

In [23]:
dfm["Result"].value_counts()

Result
NEGATIVE         1322
PENDING           665
POSITIVE          504
INDETERMINATE       3
Name: count, dtype: int64

In [25]:
# save the cleaned data
dfm = dfm[dfm["Result"] != "PENDING"]
dfm.to_csv(r"C:\Users\Dell\Documents\my_linux\repos_\predicting-covid19-infection\predicting_covid19_infection\data\raw\cleaned_covid.csv", index=False)